import React, { useState, useRef, useEffect } from "react";
// Image imports remain the same
import Gallery1 from "../../images/Gallery1.png";
import Gallery3 from "../../images/Gallery3.png";
import Gallery2 from "../../images/Gallery2.png";
import Gallery4 from "../../images/Gallery4.png";
import Gallery5 from "../../images/Gallery5.png";
import Gallery6 from "../../images/Gallery6.png";
import Gallery7 from "../../images/Gallery7.png";

const GalleryCard = ({ src, alt, className, isActive, onClick }) => {
  const activeImageClass = isActive ? "scale-110" : "";
  const activeOverlayClass = isActive ? "scale-100 inset-3" : "scale-0";
  const activeTextClass = isActive ? "translate-y-0" : "translate-y-full";

  return (
    <div
      onClick={onClick}
      className={`relative group overflow-hidden rounded-lg shadow-lg cursor-pointer ${className}`}
    >
      <img
        src={src}
        alt={alt}
        className={`w-full h-full object-cover transition-transform duration-1000 ${activeImageClass} group-hover:scale-110`}
      />
      <div
        className={`absolute inset-0 bg-red-600/40 border rounded-md border-[var(--color-primary)] transition-all duration-1000 origin-center 
            ${activeOverlayClass} group-hover:scale-100 group-hover:inset-3`}
      ></div>
      <div
        className={`absolute bottom-0 left-0 w-full p-4 transition-transform duration-500 
            ${activeTextClass} group-hover:translate-y-0`}
      >
        <h1 className="text-2xl font-bold font-zen">Bagwaan</h1>
        <p className="text-md text-gray-300 font-semibold">
          Art By <span className="text-[var(--color-primary)]">XYZ</span>
        </p>
      </div>
    </div>
  );
};

const Gallery = () => {
  const [activeCardId, setActiveCardId] = useState(null);

  const galleryRef = useRef(null);

  const handleCardClick = (id) => {
    setActiveCardId(activeCardId === id ? null : id);
  };

  useEffect(() => {
    const handleClickOutside = (event) => {
      if (galleryRef.current && !galleryRef.current.contains(event.target)) {
        setActiveCardId(null);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);

    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []); 


  return (
    <div 
      ref={galleryRef} 
      className="Gallery bg-[#0b0008] text-white py-6 md:py-16 px-4"
    >
      {/* Heading Section (No change) */}
      <div className="text-center max-w-[1531px] mx-auto mb-8 md:mb-12">
        <h2
          className="text-22 sm:text-[32px] md:text-[48px] font-normal mb-2 md:mb-4 font-zen
          leading-[100%] tracking-[0%] text-[var(--color-text)] w-full"
        >
          Popular NFT's generated by Artists
        </h2>
        <p className="text-[var(--color-text)] text-[12px] sm:text-[14px] md:text-[24px] font-normal leading[100%] tracking-[0%] w-full">
          3dotlink's AI integration is a game-changer in the NFT art world. It
          offers a powerful canvas for artists to redefine art creation and
          innovation while preserving cultural art in an entirely new format.
          With this platform, the convergence of human ingenuity and AI
          technology is set to redefine the boundaries of artistic expression
          and creative possibilities, ushering in a digital art renaissance.
        </p>
      </div>

      {/* Grid Section */}
      <div className="flex sm:flex-row gap-6 2xl:px-1 sm:mx-8 px-2  max-w-[1600px] 
      mx-auto justify-center flex-col sm:items-start items-center 2xl:mx-30 ">
        {/* Card 1 & 4 */}
        <div className="flex flex-col gap-5 sm:items-start items-center">
          {/* Card 1 */}
          <GalleryCard
            src={Gallery1}
            alt="Ancient Warrior"
            className="w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[377px]"
            isActive={activeCardId === 'card1'}
            onClick={() => handleCardClick('card1')}
          />

          {/* Card 4 */}
          <GalleryCard
            src={Gallery4}
            alt="Mystic Creation"
            className="w-full max-w-[280px] h-[280px] sm:h-[792px] sm:max-w-[377px]"
            isActive={activeCardId === 'card4'}
            onClick={() => handleCardClick('card4')}
          />
        </div>

        {/* Card 2,3,5,6 & 7*/}
        <div className="flex flex-col gap-6 sm:items-start items-center">
          {/* Card 2,3,5*/}
          <div className="flex sm:flex-row flex-col gap-6">
            {/* Card 2 */}
            <GalleryCard
              src={Gallery2}
              alt="Divine Mask"
              className="w-full max-w-[280px] h-[280px] sm:h-[787px] sm:max-w-[785px]"
              isActive={activeCardId === 'card2'}
              onClick={() => handleCardClick('card2')}
            />

            {/* Card 3 & 5 */}
            <div className="flex flex-col gap-6 sm:items-start items-center justify-between">
              {/* Card 3 */}
              <GalleryCard
                src={Gallery3}
                alt="Sacred Guardian"
                className="w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[377px]"
                isActive={activeCardId === 'card3'}
                onClick={() => handleCardClick('card3')}
              />

              {/* Card 5 */}
              <GalleryCard
                src={Gallery5}
                alt="Masked Legend"
                className="w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[377px]"
                isActive={activeCardId === 'card5'}
                onClick={() => handleCardClick('card5')}
              />
            </div>
          </div>

          {/* Card 6 & 7 */}
          <div className="flex sm:flex-row flex-col gap-6 w-full sm:items-start items-center justify-between ">
            {/* Card 6 */}
            <GalleryCard
              src={Gallery6}
              alt="Royal Protector"
              className="w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[377px]"
              isActive={activeCardId === 'card6'}
              onClick={() => handleCardClick('card6')}
            />

            {/* Card 7 */}
            <GalleryCard
              src={Gallery7}
              alt="Eternal Spirit"
              className="w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[771px]"
              isActive={activeCardId === 'card7'}
              onClick={() => handleCardClick('card7')}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Gallery;