import React from "react";
import Gallery1 from "../../images/gallery1.png";
import Gallery2 from "../../images/gallery2.png";
import Gallery3 from "../../images/gallery3.png";
import Gallery4 from "../../images/gallery4.png";
import Gallery5 from "../../images/gallery5.png";
import Gallery6 from "../../images/gallery6.png";
import Gallery7 from "../../images/gallery7.png";

const Gallery = () => {
  return (
    <div className="Gallery bg-[#0b0008] text-white py-6 md:py-16 px-4">
      {/* Heading Section */}
      <div className="text-center max-w-[1531px] mx-auto mb-8 md:mb-12">
        <h2
          className="text-22 sm:text-[32px] md:text-[48px] font-normal mb-2 md:mb-4 font-zen
         leading-[100%] tracking-[0%] text-[var(--color-text)] w-full"
        >
          Popular NFT's generated by Artists
        </h2>
        <p className="text-[var(--color-text)] text-[12px] sm:text-[14px] md:text-[24px] font-normal leading[100%] tracking-[0%] w-full">
          3dotlink's AI integration is a game-changer in the NFT art world. It
          offers a powerful canvas for artists to redefine art creation and
          innovation while preserving cultural art in an entirely new format.
          With this platform, the convergence of human ingenuity and AI
          technology is set to redefine the boundaries of artistic expression
          and creative possibilities, ushering in a digital art renaissance.
        </p>
      </div>

      {/* Grid Section */}
      <div className="flex sm:flex-row gap-6 max-w-[1600px] mx-auto flex-col sm:items-start items-center">
        {/* Card 1 & 4 */}
        <div className="flex flex-col gap-6 sm:items-start items-center">
          {/* Card 1 */}
          <div className="relative group overflow-hidden rounded-lg shadow-lg 
            w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[377px]">
            <img
              src={Gallery1}
              alt="Ancient Warrior"
              className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
            />
            <div className="absolute inset-0 bg-red-600/40 border rounded-md border-[var(--color-primary)]
              scale-0 group-hover:scale-100 group-hover:inset-3 transition-all duration-1000 origin-center"></div>
            <div className="absolute bottom-0 left-0 w-full p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-500">
              <h1 className="text-2xl font-bold font-zen">Bagwaan</h1>
              <p className="text-md text-gray-300 font-semibold">
                Art By <span className="text-[var(--color-primary)]">XYZ</span>
              </p>
            </div>
          </div>

          {/* Card 4 */}
          <div className="relative group overflow-hidden rounded-lg shadow-lg 
            w-full max-w-[280px] h-[280px] sm:h-[792px] sm:max-w-[377px]">
            <img
              src={Gallery4}
              alt="Mystic Creation"
              className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
            />
            <div className="absolute inset-0 bg-red-600/40 border rounded-md border-[var(--color-primary)]
              scale-0 group-hover:scale-100 group-hover:inset-3 transition-all duration-1000 origin-center"></div>
            <div className="absolute bottom-0 left-0 w-full p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-500">
              <h1 className="text-2xl font-bold font-zen">Bagwaan</h1>
              <p className="text-md text-gray-300 font-semibold">
                Art By <span className="text-[var(--color-primary)]">XYZ</span>
              </p>
            </div>
          </div>
        </div>

        {/* Card 2,3,5,6 & 7*/}
        <div className="flex flex-col gap-6 sm:items-start items-center">

          {/* Card 2,3,5*/}
          <div className="flex sm:flex-row flex-col gap-6">
            {/* Card 2 */}
            <div className="relative group overflow-hidden rounded-lg shadow-lg 
              w-full max-w-[280px] h-[280px] sm:h-[787px] sm:max-w-[785px]">
              <img
                src={Gallery2}
                alt="Divine Mask"
                className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
              />
              <div className="absolute inset-0 bg-red-600/40 border rounded-md border-[var(--color-primary)]
                scale-0 group-hover:scale-100 group-hover:inset-3 transition-all duration-1000 origin-center"></div>
              <div className="absolute bottom-0 left-0 w-full p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-500">
                <h1 className="text-2xl font-bold font-zen">Bagwaan</h1>
                <p className="text-md text-gray-300 font-semibold">
                  Art By <span className="text-[var(--color-primary)]">XYZ</span>
                </p>
              </div>
            </div>

            {/* Card 3 & 5 */}
            <div className="flex flex-col gap-6 sm:items-start items-center justify-between  ">
              {/* Card 3 */}
              <div className="relative group overflow-hidden rounded-lg shadow-lg 
                w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[377px]">
                <img
                  src={Gallery3}
                  alt="Sacred Guardian"
                  className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
                />
                <div className="absolute inset-0 bg-red-600/40 border rounded-md border-[var(--color-primary)]
                  scale-0 group-hover:scale-100 group-hover:inset-3 transition-all duration-1000 origin-center"></div>
                <div className="absolute bottom-0 left-0 w-full p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-500">
                  <h1 className="text-2xl font-bold font-zen">Bagwaan</h1>
                  <p className="text-md text-gray-300 font-semibold">
                    Art By <span className="text-[var(--color-primary)]">XYZ</span>
                  </p>
                </div>
              </div>

              {/* Card 5 */}
              <div className="relative group overflow-hidden rounded-lg shadow-lg 
                w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[377px]">
                <img
                  src={Gallery5}
                  alt="Masked Legend"
                  className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
                />
                <div className="absolute inset-0 bg-red-600/40 border rounded-md border-[var(--color-primary)]
                  scale-0 group-hover:scale-100 group-hover:inset-3 transition-all duration-1000 origin-center"></div>
                <div className="absolute bottom-0 left-0 w-full p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-500">
                  <h1 className="text-2xl font-bold font-zen">Bagwaan</h1>
                  <p className="text-md text-gray-300 font-semibold">
                    Art By <span className="text-[var(--color-primary)]">XYZ</span>
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Card 6 & 7 */}
          <div className="flex sm:flex-row flex-col gap-6 w-full sm:items-start items-center justify-between ">
            {/* Card 6 */}
            <div className="relative group overflow-hidden rounded-lg shadow-lg 
              w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[377px]">
              <img
                src={Gallery6}
                alt="Royal Protector"
                className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
              />
              <div className="absolute inset-0 bg-red-600/40 border rounded-md border-[var(--color-primary)]
                scale-0 group-hover:scale-100 group-hover:inset-3 transition-all duration-1000 origin-center"></div>
              <div className="absolute bottom-0 left-0 w-full p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-500">
                <h1 className="text-2xl font-bold font-zen">Bagwaan</h1>
                <p className="text-md text-gray-300 font-semibold">
                  Art By <span className="text-[var(--color-primary)]">XYZ</span>
                </p>
              </div>
            </div>

            {/* Card 7 */}
            <div className="relative group overflow-hidden rounded-lg shadow-lg 
              w-full max-w-[280px] h-[280px] sm:h-[377px] sm:max-w-[771px]">
              <img
                src={Gallery7}
                alt="Eternal Spirit"
                className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
              />
              <div className="absolute inset-0 bg-red-600/40 border rounded-md border-[var(--color-primary)]
                scale-0 group-hover:scale-100 group-hover:inset-3 transition-all duration-1000 origin-center"></div>
              <div className="absolute bottom-0 left-0 w-full p-4 translate-y-full group-hover:translate-y-0 transition-transform duration-500">
                <h1 className="text-2xl font-bold font-zen">Bagwaan</h1>
                <p className="text-md text-gray-300 font-semibold">
                  Art By <span className="text-[var(--color-primary)]">XYZ</span>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Gallery;
